ALTER TABLE Customer DROP FOREIGN KEY FKCustomer38563;
ALTER TABLE Admin DROP FOREIGN KEY FKAdmin665291;
ALTER TABLE Statement DROP FOREIGN KEY FKStatement838363;
ALTER TABLE Account DROP FOREIGN KEY FKAccount727465;
ALTER TABLE Log DROP FOREIGN KEY FKLog704853;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS Statement;
DROP TABLE IF EXISTS `User`;

